import {jsPDF} from 'jspdf';

export const runtime='nodejs';
type Values=Record<string,unknown>;
const clean=(input:unknown)=>String(input??'').replace(/[\u0000-\u001f]/g,' ').replace(/[✓√]/g,'X').replace(/²/g,'2').replace(/[—–]/g,'-');
const blank='';
const val=(v:Values,key:string)=>clean(v[key]??blank);
const selected=(v:Values,key:string,choice:string)=>val(v,key).toUpperCase()===choice.toUpperCase();

const conditionGroups:[string,[string,string,string[]][]][]=[
 ['1. STRUKTUR',[['structure-0','Pondasi',['ada, kondisi baik, kokoh','ada, sebagian rapuh, tidak kokoh','tidak ada, seluruhnya rapuh']],['structure-1','Sloof',['ada, kondisi baik, kokoh','ada, sebagian rapuh, tidak kokoh','tidak ada, seluruhnya rapuh']],['structure-2','Kolom',['ada, kondisi baik, kokoh','ada, sebagian rapuh, tidak kokoh','tidak ada, seluruhnya rapuh']],['structure-3','Ring Balok',['ada, kondisi baik, kokoh','ada, sebagian rapuh, tidak kokoh','tidak ada, seluruhnya rapuh']],['structure-4','Rangka Atap',['ada, kondisi baik, kokoh','ada, sebagian rapuh, tidak kokoh','tidak ada, seluruhnya rapuh']]]],
 ['2. NON-STRUKTUR',[['wall','Dinding',['Tembok/setengah tembok diplester, papan kayu berkualitas, bahan dinding dengan kondisi kokoh dan kedap air','Tembok kondisi sebagian besar retak, papan atau bahan lain yang kurang kokoh dan tidak kedap air','Anyaman bambu tipis, triplek, papan, tembok, atau bahan lain yang rapuh dan tidak kedap air']],['floor','Lantai',['Plester/ubin/keramik/papan/bahan lain kondisi baik, kedap air','Papan atau bahan lain dengan kondisi rusak, plester sebagian besar pecah','Tanah, papan atau bahan lain yang rapuh dan tidak kedap air']],['roof','Penutup Atap',['Genteng/seng/spandek, bahan tradisional (ijuk/rumbia)/bahan lain kondisi baik, tidak bocor','Genteng/seng/spandek, bahan tradisional (ijuk/rumbia)/bahan lain, kondisi rusak sebagian, bocor jika terjadi hujan lebat','Asbes, bahan non asbes dengan kondisi rusak berat, sering bocor jika hujan, rawan ambruk']]]],
 ['3. KESEHATAN & KECUKUPAN LUAS',[['water','Akses Air Minum',['Ada','-','Tidak Ada']],['sanitation','Akses Sanitasi',['Ada, Septictank, kamar mandi berfungsi','Ada, Septictank, kamar mandi rusak, kurang berfungsi','Tidak Ada']],['light','Pencahayaan',['Terang, dapat digunakan membaca dengan normal tanpa pencahayaan buatan pada siang hari','kurang terang sehingga kurang jelas untuk membaca dengan normal, memerlukan pencahayaan buatan pada siang hari','Gelap, tidak dapat digunakan untuk membaca tanpa pencahayaan buatan pada siang hari']],['ventilation','Penghawaan',['Cukup ventilasi, sirkulasi udara baik','ventilasi kurang, agak pengap','Tidak ada ventilasi, pengap, lembab']],['area','Kecukupan luas ruang',['Luas rumah dibagi jumlah penghuni, lebih atau sama dengan 7,2 m2','luas rumah dibagi jumlah penghuni, kurang dari 7,2 m2','Luas rumah dibagi jumlah penghuni, kurang dari 7,2 m2']]]],
 ['4. STATUS LAHAN',[['land','Status lahan',['Milik sendiri, ada bukti sah','Penguasaan lahan (pakai/izin tinggal/menumpang, ada bukti keterangan)','Tanpa bukti sah/keterangan']]]]
];
const materialOld=['Kayu','Balok Kayu','Kusen','Daun Pintu','Jendela','...','Genteng','Batu Bata','...','...'];
const materialNew=['Kayu','Genteng','Batu Bata','Pasir','Kerikil','...','...'];

export async function POST(request:Request){
 let payload:{values?:Values;year?:string;notes?:string};
 try{payload=await request.json()}catch{return Response.json({error:'Permintaan PDF tidak valid.'},{status:400})}
 const v=payload.values;
 if(!v||typeof v!=='object')return Response.json({error:'Data verifikasi tidak tersedia.'},{status:400});
 const doc=new jsPDF({orientation:'portrait',unit:'mm',format:[216,330],compress:true});
 const L=25,R=191,W=166; let y=0;
 const text=(s:unknown,x:number,yy:number,size=7,style:'normal'|'bold'|'italic'='normal',align:'left'|'center'|'right'='left')=>{doc.setFont('times',style);doc.setFontSize(size);doc.text(Array.isArray(s)?s.map(clean):clean(s),x,yy,{align});};
 const lines=(s:unknown,width:number,size=7)=>{doc.setFont('times','normal');doc.setFontSize(size);return doc.splitTextToSize(clean(s),width) as string[]};
 const box=(x:number,yy:number,w:number,h:number)=>{doc.setDrawColor(0);doc.setLineWidth(.16);doc.rect(x,yy,w,h)};
 const check=(x:number,yy:number,on:boolean)=>{box(x,yy,2.5,2.5);if(on)text('X',x+1.25,yy+2.1,6,'bold','center')};
 const lineField=(label:string,value:string,x:number,yy:number,w:number)=>{text(label,x,yy,7);text(':',x+w*.35,yy,7);doc.setLineWidth(.12);doc.line(x+w*.38,yy+1,x+w,yy+1);if(value)text(value,x+w*.38,yy-.25,7);};
 const pageNo=(n:number)=>text(`-  ${n}  -`,108,12,9,'normal','center');
 const tableLine=(x:number,yy:number,w:number,h:number)=>box(x,yy,w,h);
 pageNo(1);
 text('LEMBARAN HASIL VERIFIKASI FAKTUAL',108,27,11,'normal','center');
 text('CALON PENERIMA BANTUAN BEDAH RUMAH',108,32,11,'normal','center');
 box(L,37,30,10);text('No. Urut BNBA',L+2,41,6.5);text(val(v,'field-bnba'),L+2,45.5,7.5,'bold');
 const leftFields:[string,string][]=[['Nama KK','field-name'],['NIK','field-nik'],['Nomor KK','field-kk'],['Jenis Kelamin (L/P)','field-gender'],['Umur','field-age'],['Alamat KK','field-address'],['RT/RW','field-rtrw'],['Desa/Kelurahan','field-village'],['Kecamatan','field-district'],['Kabupaten/Kota','field-region'],['Provinsi','field-province']];
 const rightFields:[string,string][]=[['Penghasilan KK per bulan (Rp)','field-income'],['Nilai UMP/UMK (pilih yg tertinggi)','field-ump'],['Pernah dapat Bedah Rumah/BSPS/FLPP/BP2BT/Lainnya','field-prior-help'],['Jenis bantuan/program perumahan yang pernah diterima','field-help-type'],['tahun dapat Bedah Rumah/BSPS/FLPP/BP2BT/Lainnya, (isi 0 jika tidak)','field-help-year'],['Berapa tahun menghuni rumah (tulis angka)','field-occupancy-years'],['Memiliki aset rumah lainnya','field-other-home'],['Jumlah penghuni (jiwa)','field-occupants'],['Luas rumah (m2)','field-house-area'],['Bersedia mengikuti ketentuan program','field-program-agree'],['Titik Koordinat','field-coordinate']];
 y=50; for(let i=0;i<leftFields.length;i++){lineField(leftFields[i][0],val(v,leftFields[i][1]),L,y,72);const [label,key]=rightFields[i];const wrap=lines(label,47,6.8);text(wrap,108,y-(wrap.length>1?2:0),6.8);text(':',164,y,7);doc.line(166,y+1,188,y+1);if(val(v,key))text(val(v,key),166,y-.25,7);y+=5.15;}
 const foot='BNBA = by name by address, KK = kepala keluarga, NIK = Nomor Induk Kependudukan, L = laki-laki, P = perempuan, RT = rukun tetangga, RW = rukun warga, UMP = upah minimum provinsi, UMK = upah minimum kabupaten, BSPS = Bantuan Stimulan Perumahan Swadaya, FLPP = Fasilitas Likuiditas Pembiayaan Perumahan, BP2BT = Bantuan Pembiayaan Perumahan Berbasis Tabungan, m2 = meter persegi, DTSEN = Data Tunggal Sosial Ekonomi Nasional, WNI = warga negara Indonesia';
 text(lines(foot,W,5.4),L,112,5.4);
 y=121;
 const col=[26,6,41,6,41,6,40]; const x=[L]; for(const c of col)x.push(x[x.length-1]+c);
 box(L,y,W,8);box(L,y,26,8);text(['ASPEK/','KOMPONEN'],L+13,y+3,6.2,'normal','center');text('KONDISI RUMAH',L+96,y+3,6.5,'normal','center');
 for(let i=1;i<7;i++)box(x[i],y+4,col[i],4);text('A',x[1]+26,y+7,6.5,'normal','center');text('B',x[3]+26,y+7,6.5,'normal','center');text('C',x[5]+18,y+7,6.5,'normal','center');y+=8;
 for(const [group,items] of conditionGroups){box(L,y,W,4);text(group,L+W/2,y+2.8,6.5,'normal','center');y+=4;for(const [key,label,opts] of items){const opLines=opts.map((o,i)=>lines(o,[36,36,35][i],5));const h=Math.max(5.5,...opLines.map(a=>a.length*2.3+2.6));for(let ci=0;ci<7;ci++)tableLine(x[ci],y,col[ci],h);text(lines(label,24,6.2),L+1,y+2.7,6.2);for(let option=0;option<3;option++){const base=1+option*2;check(x[base]+4,y+2.1,selected(v,`condition-${key}`,'ABC'[option]));text(opLines[option],x[base+1]+1,y+2.5,5);}y+=h;}}
 const hints=['Petunjuk Pengisian:','1. Isilah dengan tanda v','2. TPM perlu melampirkan foto pada tanda (Foto) dan dicentang bila dilampirkan','3. Informasi dapat ditambahkan berdasarkan kebutuhan','4. Isian format ini sebagai format penilaian kualitas rumah dan identifikasi kebutuhan perbaikan rumah','5. Dokumentasikan (foto) kerusakan rumah yang diisi dan tiap komponen yang diperiksa.','6. Surat keterangan kepemilikan tanah/penguasaan fisik bidang tanah yang dapat diusulkan pada saat penyampaian sebelum verifikasi faktual.','Keterangan:','1. Semua bentuk rumah dan bahan bangunan rumah dinilai meliputi: rumah tembok, rumah setengah tembok, rumah kayu tapak, rumah kayu panggung.','2. Kategori rumah tidak layak huni jika memenuhi minimal 1 (satu) dari kondisi berikut:','   a. salah satu komponen struktur bernilai C;','   b. salah satu komponen non-struktur maksimal bernilai B;','   c. salah satu komponen non-struktur bernilai C; dan/atau','   d. komponen kesehatan dan kecukupan luas salah satunya bernilai C.','3. Kriteria Penerima Bantuan (syarat administrasi Bedah Rumah) mengacu pada ketentuan yang berlaku.'];
 box(L,y,W,39);let hy=y+3;for(const h of hints){text(lines(h,W-3,4.6),L+2,hy,4.6);hy+=h.startsWith('Keterangan')?3.5:2.65;}
 // page 2
 doc.addPage();pageNo(2);y=24;text('I.   IDENTIFIKASI KESWADAYAAN',L,y,8);y+=5;text('Keswadayaan disiapkan hingga pada tahap penyusunan proposal',L,y,7.5);y+=8;
 const resourceHeader=(x0:number,yy:number,w:number,title:string)=>{box(x0,yy,w,5);text(title,x0+3,yy+3.4,6.8);};
 const smallResource=(x0:number,yy:number,w:number,title:string,items:string[],prefix:string)=>{resourceHeader(x0,yy,w,title);const ws=[7,23,11,14,19,10];let xx=x0;const heads=['No','Bentuk','Ada','Tidak Ada','Jika Ada, Jumlah','Ceklis Foto'];for(let i=0;i<ws.length;i++){box(xx,yy+5,ws[i],6);text(lines(heads[i],ws[i]-1,5.5),xx+ws[i]/2,yy+7.1,5.5,'normal','center');xx+=ws[i]}let ry=yy+11;items.forEach((item,index)=>{xx=x0;for(const ww of ws){box(xx,ry,ww,5);xx+=ww}text(String(index+1),x0+3.5,ry+3.3,5.8,'normal','center');text(item,x0+9,ry+3.3,5.8);check(x0+34,ry+1.25,selected(v,`${prefix}-${index}-available`,'Ada'));check(x0+46,ry+1.25,selected(v,`${prefix}-${index}-available`,'Tidak ada'));if(val(v,`${prefix}-${index}-value`))text(val(v,`${prefix}-${index}-value`),x0+56,ry+3.3,5.4);check(x0+78,ry+1.25,selected(v,`${prefix}-${index}-photo`,'on'));ry+=5;});return ry;};
 box(L,y,W,5);text('A. Barang/Material',L+3,y+3.3,6.8);y+=5;const ym=y;const endOld=smallResource(L,y,83,'a.   Material Eksisting/Bekas Layak Pakai',materialOld,'material-used');const endNew=smallResource(L+83,y,83,'b.   Material Baru/Stok',materialNew,'material-new');y=Math.max(endOld,endNew)+5;
 const broadResource=(title:string,items:string[],prefix:string)=>{resourceHeader(L,y,W,title);const ws=[9,61,14,16,66];let xx=L;const heads=['No','Sumber','Ada','Tidak Ada',prefix==='money'?'Jika Ada, Nilai (Rp)':'Jika Ada, Sebutkan Nama'];for(let i=0;i<ws.length;i++){box(xx,y+5,ws[i],6);text(lines(heads[i],ws[i]-1,5.5),xx+1,y+8,5.5);xx+=ws[i]}let ry=y+11;items.forEach((item,index)=>{xx=L;for(const ww of ws){box(xx,ry,ww,5);xx+=ww}text(String(index+1),L+4.5,ry+3.3,5.8,'normal','center');text(item,L+11,ry+3.3,5.8);check(L+75,ry+1.25,selected(v,`${prefix}-${index}-available`,'Ada'));check(L+89,ry+1.25,selected(v,`${prefix}-${index}-available`,'Tidak ada'));if(val(v,`${prefix}-${index}-value`))text(val(v,`${prefix}-${index}-value`),L+102,ry+3.3,5.4);ry+=5;});y=ry+5;};
 broadResource('B. Uang',['Tabungan','Hasil jual panen/ternak','Bantuan keluarga/kerabat','Lainnya ...'],'money');broadResource('C. Tenaga Kerja',['Tenaga Sendiri','Dukungan keluarga','Dukungan tetangga/kerabat','Lainnya ...'],'labor');
 text('II.   KESIMPULAN',L,y,8);y+=3;
 const rec=val(v,'assessment-recommendation').toLowerCase().includes('direkomendasikan')&&!val(v,'assessment-recommendation').toLowerCase().includes('tidak');
 const cy=y,lh=32;box(L,cy,W,lh);doc.line(L,cy+6,L+W,cy+6);doc.line(L+50,cy,L+50,cy+lh);text('Direkomendasikan Bedah Rumah',L+5,cy+4,6.5);check(L+45,cy+1.7,rec);text('Tidak Direkomendasikan Bedah Rumah, Alasan:',L+57,cy+4,6.5);check(L+52,cy+1.7,!rec);
 doc.line(L+50,cy+15,L+W,cy+15);doc.line(L+50,cy+24,L+W,cy+24);doc.line(L+89,cy+6,L+89,cy+lh);doc.line(L+128,cy+6,L+128,cy+lh);doc.line(L,cy+19,L+50,cy+19);
 check(L+6,cy+9,selected(v,'field-construction','Konvensional'));text('Konvensional',L+12,cy+11.5,6.1);check(L+6,cy+22,selected(v,'field-construction','Ferosemen'));text(['Ferosemen (untuk rumah','tembok tanpa struktur)'],L+12,cy+24.5,6.1);
 const reason=(x0:number,yy:number,label:string,on:boolean)=>{check(x0,yy,on);text(lines(label,32,5.1),x0+4,yy+2.2,5.1)};
 reason(L+53,cy+8,'Belum memiliki KK sendiri',val(v,'field-own-kk')==='Tidak');reason(L+92,cy+8,'Memiliki rumah >1',val(v,'field-other-home')==='Ya');reason(L+131,cy+8,'Memilih program lain',val(v,'field-other-program')==='Ya');
 reason(L+53,cy+17,'Tanah bersengketa/tanpa bukti sah kepemilikan/penguasaan/ilegal',val(v,'field-dispute')==='Ya');reason(L+92,cy+17,'Pernah memperoleh Bedah Rumah/BSPS/FLPP/BP2BT/lainnya bagi MBR dalam 5 tahun terakhir',val(v,'field-prior-help')==='Ya');reason(L+131,cy+17,'Rumah yang ditinggali <1 tahun',val(v,'field-occupancy-years')!==''&&Number(val(v,'field-occupancy-years'))<1);
 reason(L+53,cy+26,'Rumah layak huni/rusak ringan',val(v,'assessment-housing-status').includes('Layak'));reason(L+92,cy+26,'Penghasilan > UMP/UMK',Number(val(v,'field-income'))>Number(val(v,'field-ump')));y=cy+38; text('III. Pernyataan',L,y,8);y+=4;text('Calon Penerima Bantuan (CPB) sanggup mengikuti ketentuan program dan tidak akan mengundurkan diri.',L+5,y,6.8);y+=9;text('...,  ... 20...',148,y,6.8);y+=8;[['Diperiksa oleh,','Koordinator Kabupaten/Kota','field-coordinator'],['Diketahui oleh,','Calon Penerima Bantuan','field-recipient'],['Dilakukan oleh,','Tenaga Pendamping Masyarakat','field-tpm']].forEach(([a,b,k],i)=>{const x0=L+30+i*56;text(a,x0,y,7,'normal','center');text(b,x0,y+4,7,'normal','center');text('tanda tangan',x0,y+12,7,'italic','center');text(val(v,k)||'nama tanpa gelar',x0,y+23,7,'normal','center');});
 doc.setProperties({title:`Lembar Verifikasi ${val(v,'field-bnba')}`,subject:'Verifikasi Faktual CPB'});
 return new Response(new Uint8Array(doc.output('arraybuffer')),{headers:{'Content-Type':'application/pdf','Content-Disposition':`inline; filename="lembar-verifikasi-${val(v,'field-bnba')}.pdf"`,'Cache-Control':'no-store'}});
}
