import {jsPDF} from 'jspdf';

export const runtime='nodejs';
type Values=Record<string,unknown>;
const text=(value:unknown)=>String(value??'').replace(/[\u0000-\u001f]/g,' ').replace(/[✓√]/g,'X').replace(/²/g,'2').replace(/[—–]/g,'-');
const value=(values:Values,key:string,empty='................................')=>text(values[key]===undefined||values[key]===''?empty:values[key]);
const mark=(selected:boolean)=>selected?'[X]':'[ ]';
const resourceSets:[string,string[],string][]=[['a. Material Eksisting/Bekas Layak Pakai',['Kayu','Balok kayu','Kusen','Daun pintu','Jendela','Genteng','Batu bata','Lainnya'],'material-used'],['b. Material Baru/Stok',['Kayu','Genteng','Batu bata','Pasir','Kerikil','Lainnya'],'material-new'],['B. Uang',['Tabungan','Hasil jual panen/ternak','Bantuan keluarga/kerabat','Lainnya'],'money'],['C. Tenaga Kerja',['Tenaga sendiri','Dukungan keluarga','Dukungan tetangga/kerabat','Lainnya'],'labor']];
const groups:[string,[string,string,string[]][]][]=[['1. STRUKTUR',[['structure-0','Pondasi',['Ada, kondisi baik, kokoh','Ada, sebagian rapuh, tidak kokoh','Tidak ada, seluruhnya rapuh']],['structure-1','Sloof',['Ada, kondisi baik, kokoh','Ada, sebagian rapuh, tidak kokoh','Tidak ada, seluruhnya rapuh']],['structure-2','Kolom',['Ada, kondisi baik, kokoh','Ada, sebagian rapuh, tidak kokoh','Tidak ada, seluruhnya rapuh']],['structure-3','Ring Balok',['Ada, kondisi baik, kokoh','Ada, sebagian rapuh, tidak kokoh','Tidak ada, seluruhnya rapuh']],['structure-4','Rangka Atap',['Ada, kondisi baik, kokoh','Ada, sebagian rapuh, tidak kokoh','Tidak ada, seluruhnya rapuh']]]],['2. NON-STRUKTUR',[['wall','Dinding',['Tembok/setengah tembok diplester, papan kayu berkualitas, bahan dinding kokoh dan kedap air','Tembok sebagian besar retak, papan atau bahan lain kurang kokoh dan tidak kedap air','Anyaman bambu tipis, triplek, papan, tembok, atau bahan lain rapuh dan tidak kedap air']],['floor','Lantai',['Plester/ubin/keramik/papan/bahan lain kondisi baik, kedap air','Papan atau bahan lain rusak, plester sebagian besar pecah','Tanah, papan, atau bahan lain rapuh dan tidak kedap air']],['roof','Penutup Atap',['Genteng/seng/spandek/bahan tradisional/bahan lain kokoh, tidak bocor','Genteng/seng/spandek/bahan tradisional/bahan lain sebagian rusak, bocor jika hujan lebat','Asbes, bahan non-asbes rusak berat, sering bocor jika hujan, rawan ambruk']]]],['3. KESEHATAN DAN KECUKUPAN LUAS',[['water','Akses Air Minum',['Ada','-','Tidak ada']],['sanitation','Akses Sanitasi',['Ada, septic tank, kamar mandi berfungsi','Ada, septic tank, kamar mandi rusak, kurang berfungsi','Tidak ada']],['light','Pencahayaan',['Terang, dapat digunakan membaca tanpa pencahayaan buatan pada siang hari','Kurang terang, perlu pencahayaan buatan pada siang hari','Gelap, tidak dapat digunakan membaca tanpa pencahayaan buatan']],['ventilation','Penghawaan',['Cukup ventilasi, sirkulasi udara baik','Ventilasi kurang, agak pengap','Tidak ada ventilasi, pengap, lembab']],['area','Kecukupan luas ruang',['Luas rumah / penghuni >= 7,2 m2','Luas rumah / penghuni < 7,2 m2','Luas rumah / penghuni < 7,2 m2']]]],['4. STATUS LAHAN',[['land','Status Lahan',['Milik sendiri, ada bukti sah','Penguasaan lahan, ada bukti/keterangan','Tanpa bukti sah/keterangan']]]]];

export async function POST(request:Request){
 let payload:{values?:Values;year?:string;notes?:string};try{payload=await request.json()}catch{return Response.json({error:'Permintaan PDF tidak valid.'},{status:400})}
 const v=payload.values;if(!v||typeof v!=='object')return Response.json({error:'Data verifikasi tidak tersedia.'},{status:400});
 const doc=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true}),left=17,right=193,bottom=282;let y=16,page=1;
 const footer=()=>{doc.setDrawColor(0);doc.setLineWidth(.15);doc.line(left,bottom-5,right,bottom-5);doc.setFont('times','normal');doc.setFontSize(7);doc.text('Lembar Hasil Verifikasi Faktual Calon Penerima Bantuan',left,bottom);doc.text(`Halaman ${page}`,right,bottom,{align:'right'})};
 const next=()=>{footer();doc.addPage();page++;y=16};const ensure=(height:number)=>{if(y+height>274)next()};
 const heading=(label:string)=>{ensure(10);doc.setFont('times','bold');doc.setFontSize(9);doc.text(label,left,y);y+=5;doc.setLineWidth(.3);doc.line(left,y,right,y);y+=3};
 const wrapped=(content:unknown,width:number,size:number)=>{doc.setFont('times','normal');doc.setFontSize(size);return doc.splitTextToSize(text(content),width) as string[]};
 const identityRow=(l1:string,k1:string,l2:string,k2:string)=>{const col=88,a=wrapped(l1,31,7.5),b=wrapped(value(v,k1),50,7.5),c=wrapped(l2,31,7.5),d=wrapped(value(v,k2),50,7.5),h=Math.max(a.length,b.length,c.length,d.length)*3.4+1.4;ensure(h);doc.setFont('times','normal');doc.setFontSize(7.5);doc.text(a,left,y+2.6);doc.text(':',left+32,y+2.6);doc.text(b,left+36,y+2.6);doc.text(c,left+col,y+2.6);doc.text(':',left+col+32,y+2.6);doc.text(d,left+col+36,y+2.6);y+=h};
 const matrixHeader=()=>{ensure(18);doc.setFont('times','bold');doc.setFontSize(7);doc.rect(left,y,30,12);doc.rect(left+30,y,146,6);[0,1,2].forEach(i=>doc.rect(left+30+48.67*i,y+6,48.67,6));doc.text(['ASPEK/','KOMPONEN'],left+15,y+3,{align:'center'});doc.text('KONDISI RUMAH',left+103,y+3,{align:'center'});['A','B','C'].forEach((letter,i)=>doc.text(letter,left+54.3+48.67*i,y+10,{align:'center'}));y+=12};
 const matrixGroup=(name:string,items:[string,string,string[]][])=>{ensure(11);doc.setFont('times','bold');doc.setFontSize(7);doc.setFillColor(245,245,245);doc.rect(left,y,176,6,'FD');doc.text(name,left+2,y+4);y+=6;for(const [key,label,options] of items){const rows=options.map(opt=>wrapped(opt,46,6.4)),labelRows=wrapped(label,27,7),h=Math.max(labelRows.length,...rows.map(row=>row.length))*3+3;ensure(h+1);if(y===16)matrixHeader();doc.setFont('times','normal');doc.setFontSize(7);doc.rect(left,y,30,h);doc.text(labelRows,left+1,y+3);rows.forEach((row,i)=>{const x=left+30+48.67*i;doc.rect(x,y,48.67,h);doc.setFontSize(6.4);doc.text(`${mark(v[`condition-${key}`]==='ABC'[i])} ${row[0]}`,x+1,y+3);if(row.length>1)doc.text(row.slice(1),x+1,y+6)});y+=h}};
 const resourceTable=(title:string,items:string[],prefix:string,half=false,tableLeft=left)=>{const tableWidth=half?85:176,widths=half?[8,26,12,12,19,8]:[13,55,25,28,55];ensure(18+items.length*9);doc.setFont('times','bold');doc.setFontSize(7);doc.rect(tableLeft,y,tableWidth,6);doc.text(title,tableLeft+2,y+4);y+=6;let x=tableLeft;['No.','Bentuk/sumber','Ada','Tidak Ada','Jika Ada, '+(prefix==='money'?'Nilai (Rp)':prefix==='labor'?'Sebutkan nama':'Jumlah'),...(half?['Foto']:[])].forEach((label,i)=>{doc.rect(x,y,widths[i],8);doc.text(doc.splitTextToSize(label,widths[i]-1),x+1,y+3);x+=widths[i]});y+=8;items.forEach((item,index)=>{const available=v[`${prefix}-${index}-available`],detail=available==='Ada'?value(v,`${prefix}-${index}-value`):'',cells=[String(index+1),item,mark(available==='Ada'),mark(available==='Tidak ada'),detail,...(half?[mark(available==='Ada'&&v[`${prefix}-${index}-photo`]==='on')]:[])],lines=cells.map((entry,i)=>wrapped(entry,widths[i]-2,6.5)),h=Math.max(9,Math.max(...lines.map(line=>line.length))*3+3);ensure(h+1);let cx=tableLeft;lines.forEach((line,i)=>{doc.rect(cx,y,widths[i],h);doc.text(line,cx+(i===0?widths[i]/2:1),y+3,{align:i===0?'center':'left'});cx+=widths[i]});y+=h})};
 doc.setFont('times','normal');doc.setFontSize(9);doc.text('H. VERIFIKASI FAKTUAL CALON PENERIMA BANTUAN BEDAH RUMAH',left,y);y+=13;doc.setFont('times','bold');doc.setFontSize(12);doc.text('LEMBARAN HASIL VERIFIKASI FAKTUAL',105,y,{align:'center'});y+=5;doc.text('CALON PENERIMA BANTUAN BEDAH RUMAH',105,y,{align:'center'});y+=9;doc.rect(left,y,34,13);doc.setFontSize(7);doc.text('No. Urut BNBA',left+2,y+4);doc.setFontSize(9);doc.text(value(v,'field-bnba'),left+2,y+9);y+=17;
 [['Nama KK','field-name','Penghasilan KK per bulan (Rp)','field-income'],['NIK','field-nik','Nilai UMP/UMK (pilih yang tertinggi)','field-ump'],['Nomor KK','field-kk','Pernah dapat Bedah Rumah / BSPS / FLPP / BP2BT / lainnya','field-prior-help'],['Jenis Kelamin (L/P)','field-gender','Jenis bantuan/program perumahan yang pernah diterima','field-help-type'],['Umur','field-age','Tahun dapat bantuan (isi 0 jika tidak pernah)','field-help-year'],['Alamat KK','field-address','Berapa tahun menghuni rumah (tulis angka)','field-occupancy-years'],['RT/RW','field-rtrw','Memiliki aset rumah lainnya','field-other-home'],['Desa/Kelurahan','field-village','Jumlah penghuni (jiwa)','field-occupants'],['Kecamatan','field-district','Luas rumah (m2)','field-house-area'],['Kabupaten/Kota','field-region','Bersedia mengikuti ketentuan program','field-program-agree'],['Provinsi','field-province','Titik Koordinat','field-coordinate']].forEach(([a,b,c,d])=>identityRow(a,b,c,d));
 const legend='BNBA = by name by address; KK = kepala keluarga; NIK = Nomor Induk Kependudukan; L = laki-laki; P = perempuan; RT = rukun tetangga; RW = rukun warga; UMP = upah minimum provinsi; UMK = upah minimum kabupaten; BSPS = Bantuan Stimulan Perumahan Swadaya; FLPP = Fasilitas Likuiditas Pembiayaan Perumahan; BP2BT = Bantuan Pembiayaan Perumahan Berbasis Tabungan; m2 = meter persegi.';doc.setFont('times','normal');doc.setFontSize(5.5);const legendLines=doc.splitTextToSize(legend,176) as string[];ensure(legendLines.length*2.4+4);doc.text(legendLines,left,y);y+=legendLines.length*2.4+4;matrixHeader();groups.forEach(([group,items])=>matrixGroup(group,items));
 heading('I. IDENTIFIKASI KESWADAYAAN');doc.setFont('times','normal');doc.setFontSize(8);doc.text('A. Barang/Material',left,y);y+=4;const materialY=y;resourceTable(resourceSets[0][0],resourceSets[0][1],resourceSets[0][2],true);const afterLeft=y;y=materialY;resourceTable(resourceSets[1][0],resourceSets[1][1],resourceSets[1][2],true,left+91);y=Math.max(afterLeft,y)+5;resourceTable(resourceSets[2][0],resourceSets[2][1],resourceSets[2][2]);y+=4;resourceTable(resourceSets[3][0],resourceSets[3][1],resourceSets[3][2]);
 next();heading('II. KESIMPULAN');[['Status hunian','assessment-housing-status'],['Rekomendasi','assessment-recommendation'],['Jenis penanganan','field-construction'],['Keterangan hasil verifikasi',''],['Tempat, tanggal verifikasi','field-verification-date']].forEach(([label,key])=>{const detail=key?value(v,key):text(payload.notes||'');const lines=wrapped(detail,122,8),h=Math.max(1,lines.length)*4+5;ensure(h);doc.setFont('times','bold');doc.setFontSize(8);doc.rect(left,y,52,h);doc.text(label,left+2,y+4);doc.setFont('times','normal');doc.rect(left+52,y,124,h);doc.text(lines,left+54,y+4);y+=h});y+=8;doc.setFont('times','bold');doc.setFontSize(9);doc.text('III. PERNYATAAN',left,y);y+=5;doc.setFont('times','normal');doc.setFontSize(8);doc.text(doc.splitTextToSize('Calon Penerima Bantuan (CPB) sanggup mengikuti ketentuan program dan tidak akan mengundurkan diri.',176),left,y);y+=20;[['Diperiksa oleh,','Koordinator Kabupaten/Kota','field-coordinator'],['Diketahui oleh,','Calon Penerima Bantuan','field-recipient'],['Dilakukan oleh,','Tenaga Pendamping Masyarakat','field-tpm']].forEach(([line,role,key],index)=>{const x=left+index*60;doc.text(line,x,y);doc.text(role,x,y+4);doc.line(x,y+28,x+55,y+28);doc.setFont('times','bold');doc.text(value(v,key),x,y+32)});footer();doc.setProperties({title:`Lembar Verifikasi ${value(v,'field-bnba','')}`,subject:'Verifikasi Faktual CPB'});return new Response(new Uint8Array(doc.output('arraybuffer')),{headers:{'Content-Type':'application/pdf','Content-Disposition':`inline; filename="lembar-verifikasi-${value(v,'field-bnba','')}.pdf"`,'Cache-Control':'no-store'}});
}
