import {env} from 'cloudflare:workers';
import seed from './seed.json';
import sourceInfo from './source-info.json';
export const datasetVersion=sourceInfo.version+':bahv-v1';
import {mergeSources,recordKey,auditSources,kinds} from '../public/import-model.js';
export const db=()=>{const binding=(env as unknown as {DB:D1Database}).DB;if(!binding)throw new Error('Penyimpanan data belum tersedia.');return binding};
export async function revision(){const r=await db().prepare('SELECT version FROM app_state WHERE id = 1').first<{version:number}>();return r?.version||0}
export async function getSources(){const stored=await db().prepare("SELECT s.kind,s.record_key,s.payload,i.completed_at FROM source_records s JOIN imports i ON i.id=s.import_id WHERE i.status='complete'").all<{kind:string,record_key:string,payload:string,completed_at:string}>();const sources:Record<string,any[]>={};for(const kind of Object.keys(kinds)){const rows=(seed as Record<string,any[]>)[kind]||[];const map=new Map(rows.map(r=>[recordKey(r),r]));for(const s of stored.results.filter(s=>s.kind===kind&&s.completed_at>((sourceInfo.cutoffs as Record<string,string>)[kind]||'')))map.set(s.record_key,JSON.parse(s.payload));sources[kind]=[...map.values()]}return sources}
export async function getData(){const sources=await getSources();const issues=auditSources(sources);const issuesByKey=new Map<string,any[]>();for(const issue of issues){if(!issuesByKey.has(issue.key))issuesByKey.set(issue.key,[]);issuesByKey.get(issue.key)!.push(issue)}const records=mergeSources(sources).map(r=>{const {sources,...record}=r;return {...record,issueCount:(issuesByKey.get(recordKey(record))||[]).length,issue:(issuesByKey.get(recordKey(record))||[]).map(i=>i.parameter).join(' · '),verification:sources.field?.verification||'',verificationStatus:sources.field?.verificationStatus||'',reason:sources.field?.reason||'',legacyFilled:sources.legacy?.filled??null,legacyTotal:sources.legacy?.total??null,legacyPB:sources.legacy?.legacyPB||''}});const history=await db().prepare("SELECT id,kind,filename,count,completed_at,summary FROM imports WHERE status = 'complete' ORDER BY completed_at DESC LIMIT 20").all();return{records,issues,sourceInfo,counts:Object.fromEntries(Object.entries(sources).map(([k,v])=>[k,v.length])),history:history.results,revision:await revision()}}
export const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
