import {db,getSources,revision,json,datasetVersion} from '../../../lib/data';
import {kinds,validate,recordKey,normalize,replacementPreview} from '../../../public/import-model.js';
const fields=Object.keys(normalize('field',{}));
function checkRecords(kind:string,records:unknown[],validateValues=true){if(!Array.isArray(records)||records.length<1||records.length>15000)throw new Error('File harus berisi 1–15.000 baris.');for(const item of records){if(!item||typeof item!=='object')throw new Error('Struktur data impor tidak sesuai.');const record=item as Record<string,unknown>;if(fields.some(k=>!Object.hasOwn(record,k))||Object.keys(record).some(k=>!fields.includes(k)))throw new Error('Struktur data impor tidak sesuai.');for(const [key,value] of Object.entries(record)){if(['progress','filled','total'].includes(key)){if(value!==null&&(typeof value!=='number'||!Number.isFinite(value)))throw new Error('Nilai progres tidak valid.')}else if(typeof value!=='string'||value.length>(key==='verificationDetails'?15000:2000))throw new Error('Isi kolom tidak valid atau terlalu panjang.')}}const errors=validateValues?validate(kind,records):[];if(errors.length)throw new Error(errors.slice(0,8).join(' '))}
export async function POST(request:Request){const origin=request.headers.get('origin'),forwardedHost=request.headers.get('x-forwarded-host')||request.headers.get('host')||'';if(origin&&new URL(origin).host!==forwardedHost)return json({error:'Asal permintaan tidak sesuai.'},403);if(!request.headers.get('content-type')?.includes('application/json'))return json({error:'Format permintaan tidak sesuai.'},415);try{const text=await request.text();if(text.length>18_000_000)return json({error:'Ukuran data terlalu besar.'},413);const body=JSON.parse(text);const {action,kind}=body;
if(action==='preview'){if(!Object.hasOwn(kinds,kind))throw new Error('Jenis sumber tidak dikenal.');checkRecords(kind,body.records,false);const before=await revision();const sources=await getSources();if(before!==await revision())return json({error:'Data sedang diperbarui. Periksa pratinjau sekali lagi.'},409);return json({...replacementPreview(kind,body.records,sources),revision:before,datasetVersion})}
if(action==='begin'){if(!Object.hasOwn(kinds,kind))throw new Error('Jenis sumber tidak dikenal.');if(!Number.isInteger(body.count)||body.count<1||body.count>15000)throw new Error('Jumlah baris tidak valid.');if(typeof body.filename!=='string'||body.filename.length>200)throw new Error('Nama file tidak valid.');const sourceAsOf=body.sourceAsOf&&typeof body.sourceAsOf==='object'?{iso:typeof body.sourceAsOf.iso==='string'?body.sourceAsOf.iso.slice(0,50):'',label:typeof body.sourceAsOf.label==='string'?body.sourceAsOf.label.slice(0,100):''}:null;if(body.datasetVersion!==datasetVersion||!Number.isInteger(body.revision)||body.revision!==await revision())return json({error:'Data telah diperbarui. Periksa pratinjau impor kembali.'},409);const id=crypto.randomUUID();await db().prepare('INSERT INTO imports (id,kind,filename,status,count,created_at,summary) VALUES (?,?,?,?,?,?,?)').bind(id,kind,body.filename,'staging',body.count,new Date().toISOString(),JSON.stringify({baseRevision:body.revision,baseDataset:datasetVersion,mode:'replace',sourceAsOf})).run();return json({id})}
if(typeof body.id!=='string')throw new Error('Impor tidak ditemukan.');const imp=await db().prepare('SELECT * FROM imports WHERE id = ?').bind(body.id).first<{id:string,kind:string,status:string,count:number,summary:string}>();if(!imp)return json({error:'Impor tidak ditemukan.'},404);if(imp.status==='complete')return json({complete:true,summary:JSON.parse(imp.summary)});
if(action==='chunk'){const records=body.records as Array<Record<string,unknown>>;checkRecords(imp.kind,records,false);if(records.some(record=>typeof record.id!=='string'||typeof record.year!=='string'||!/^\d{6,20}$/.test(record.id)||!/^20\d{2}$/.test(record.year)))throw new Error('Nomor BNBA dan tahun harus valid untuk menyimpan.');if(records.length>100)throw new Error('Maksimal 100 baris per pengiriman.');await db().batch(records.map(record=>db().prepare('INSERT INTO staged_rows (import_id,record_key,payload) VALUES (?,?,?) ON CONFLICT(import_id,record_key) DO UPDATE SET payload=excluded.payload').bind(imp.id,recordKey(record),JSON.stringify(record))));return json({received:records.length})}
if(action==='commit'){const staged=await db().prepare('SELECT payload FROM staged_rows WHERE import_id = ?').bind(imp.id).all<{payload:string}>();if(staged.results.length!==imp.count)throw new Error('Pengiriman belum lengkap. Silakan lanjutkan impor.');const records=staged.results.map(r=>JSON.parse(r.payload));checkRecords(imp.kind,records,false);const importSummary=JSON.parse(imp.summary);const base=importSummary.baseRevision;if(importSummary.baseDataset!==datasetVersion||await revision()!==base)return json({error:'Data telah diperbarui dari impor lain. Kembali ke pratinjau sebelum melanjutkan.'},409);const summary={...replacementPreview(imp.kind,records,await getSources()),sourceAsOf:importSummary.sourceAsOf||null};if(!summary.canSubmit)return json({error:'Ada parameter tidak valid. Perbaiki file dan lakukan pemeriksaan ulang.',issues:summary.errors},422);if(!body.overwrite)return json({error:'Gunakan Simpan dan timpa sumber untuk mengganti data sumber yang dipilih.',issues:summary.issues},422);const timestamp=new Date().toISOString();await db().batch([
db().prepare('INSERT OR IGNORE INTO app_state (id,version,owner) VALUES (1,0,?)').bind(''),
db().prepare('UPDATE app_state SET version=version+1,owner=? WHERE id=1 AND version=?').bind(imp.id,base),
db().prepare('INSERT INTO source_records (kind,record_key,payload,import_id) SELECT ?,record_key,payload,? FROM staged_rows WHERE import_id=? AND EXISTS (SELECT 1 FROM app_state WHERE id=1 AND version=? AND owner=?) ON CONFLICT(kind,record_key) DO UPDATE SET payload=excluded.payload,import_id=excluded.import_id').bind(imp.kind,imp.id,imp.id,base+1,imp.id),
db().prepare("UPDATE imports SET status='complete',completed_at=?,summary=? WHERE id=? AND EXISTS (SELECT 1 FROM app_state WHERE id=1 AND version=? AND owner=?)").bind(timestamp,JSON.stringify(summary),imp.id,base+1,imp.id),
db().prepare("DELETE FROM staged_rows WHERE import_id=? AND EXISTS (SELECT 1 FROM imports WHERE id=? AND status='complete')").bind(imp.id,imp.id)
]);const done=await db().prepare('SELECT status FROM imports WHERE id = ?').bind(imp.id).first<{status:string}>();if(done?.status!=='complete')return json({error:'Data telah berubah. Periksa pratinjau impor kembali.'},409);return json({complete:true,summary})}
throw new Error('Tindakan impor tidak dikenal.');
}catch(e){console.error('Import RAB failed',e);return json({error:e instanceof Error&&!/D1|SQL|database/i.test(e.message)?e.message:'Pembaruan belum tersimpan. Coba kembali; data sebelumnya tetap tersedia.'},400)}}
